name: flutter_datalogic
description: A Flutter package communicate with Datalogic scanners.
version: 1.0.1
homepage: https://github.com/tusaamf/flutter_datalogic

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  freezed_result: ^1.0.3+1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.tusaamf.flutter_datalogic
        pluginClass: FlutterDatalogicPlugin